[package]
name = "modscraper-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
meilisearch-sdk = "0.26.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.5.0"
dotenvy = "0.15"
axum = "0.7.5"