services:
  search:
    image: getmeili/meilisearch:v1.8
    environment:
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=true
    env_file:
      - .env

  server:
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - ./assets:/assets
    env_file:
      - .env
    depends_on:
      - search